### ISSUE TITLE
Is it possible to add triples or quads with pyley?

### ISSUE THREAD

**Issue by russellballestrini** [ziyasal/pyley#24]
If yes, please provide an example and I will gladly help PR changes to the readme.

**Comment by abdullahselek** [comment]
Yes, `pyley` supports adding quads but I couldn't find a adding triples on `cayley` docs. Could you please send me if you have the link for the adding triples?

**Comment by russellballestrini** [comment]
I'm brand new to Cayley so just an example of how to add a quad to Cayley
using pyley would be really helpful.

Or a link to the docs.

**Comment by russellballestrini** [comment]
It seems that the label is optional, although I don't see why anyone would want to leave it out. A triple is a quad without a label.
