### ISSUE TITLE
I find some mistakes in the pyley guide.

### ISSUE THREAD

**Issue by HarryUlysses** [ziyasal/pyley#25]
In the guide, For example:
query = g.V("Humphrey Bogart").In("name").All()
response = client.Send(query)

you lose the '<>' near the "name".

The right answer is：
query = g.V("Humphrey Bogart").In("\<name\>").All()
response = client.Send(query)

After doing like this, then my program is work.

**Comment by abdullahselek** [comment]
@HarryUlysses thanks for letting us know readme updated. Also please feel free to open merge request when you find a bug or mistake.
