### ISSUE TITLE
release to the cheeseshop

### ISSUE THREAD

**Issue by paultag** [ziyasal/pyley#7]
it'd be great to tag releases and put them up on pypi

**Comment by ziyasal** [comment]
Hi @paultag , Thanks for your suggestion, I plan to do that asap.

**Comment by ziyasal** [comment]
Created v0.1.2 version tag and pushed package to pypi

**Comment by paultag** [comment]
You rock, thanks!

On Mon, Mar 2, 2015 at 1:44 PM, Ziya SARIKAYA <notifications@github.com>
wrote:

> Created v0.1.2 version tag and pushed package to pypi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ziyasal/pyley/issues/7#issuecomment-76776383>.
>



-- 
:wq
